In [2]:
import numpy as np

# Define the Rastrigin function as the objective function


def rastrigin(x):
    A = 10
    return A * len(x) + sum([(xi**2 - A * np.cos(2 * np.pi * xi)) for xi in x])

# Evolution Strategy Algorithm

In [3]:
# Parameters
mu = 5            # Number of parents
lambd = 20        # Number of children
dim = 5           # Dimensionality of the solution
generations = 50  # Number of generations
bounds = (-5.12, 5.12)  # Rastrigin bounds

In [4]:
population = [np.random.uniform(bounds[0], bounds[1], dim)
            for _ in range(lambd)]

In [12]:
#geting the dim of population
len(population),len(population[0])

(20, 5)

In [21]:
np.argsort(population[0])[:3]

array([0, 3, 2], dtype=int64)

In [22]:
np.argpartition(population[0],3)[:3]
#this is faster it doesn't sort the population it gives you the top 3 but not sorted and this what you want .
#the argsort sort them.

array([3, 0, 2], dtype=int64)

In [23]:
np.random.normal(0, 1, dim)

array([ 0.0644361 , -0.32506553, -0.12473504, -0.4443007 , -0.74531529])

The main difference between argsort and argpartition lies in how they retrieve the indices of the top elements in a list and how they perform with respect to computational efficiency.

1. argsort:
Description: argsort returns the indices that would sort the array in ascending order. If you want the top 5 elements, it sorts the entire array first and then selects the top 5.
Time Complexity: Sorting the entire array has a time complexity of O(n log n), where n is the number of elements in the array.
Use case: When you need the entire sorted order of elements.
2. argpartition:
Description: argpartition doesn't fully sort the array. Instead, it partitions the array around the k-th largest element (or smallest, depending on the use case), and only ensures that the top k elements are on one side (but not sorted). It’s more efficient when you only need the top k elements, not the full order.
Time Complexity: The time complexity of argpartition is O(n), which is much faster than sorting for large arrays.
Use case: When you only care about the top k elements and don't need the full sorted order.