In [17]:
import pandas as pd
import numpy as np

In [18]:
def objective_function(params):
  x,y,z=params[0],params[1],params[2]
  #single objective function
  result=(x-4)**2+(y-5)**2+(z+6)**2
  return result

In [19]:
bound=np.array([-10,10])
bound

array([-10,  10])

In [20]:
w=0.8
c1=2
c2=2
n_particle=20
max_iteration=50

In [21]:
# Intitalization of particles and velocity

In [22]:
particles=np.random.uniform(bound[0],bound[1],size=(n_particle,3))
particles

array([[ 7.33480584, -6.87304549, -4.32103639],
       [ 5.62667544, -2.48234971,  7.60685025],
       [ 8.96475458,  0.58038599,  0.42698686],
       [ 0.948659  ,  8.19242635, -1.29544667],
       [-9.39826872, -1.19121828, -1.35464897],
       [-4.20030831, -5.9378451 , -8.20321599],
       [ 2.19356288,  9.64556049,  4.28587743],
       [-3.40325295, -8.75015735,  2.89170225],
       [-5.5435454 ,  9.39492336,  4.94894756],
       [-2.89534983, -8.93688012,  0.93350165],
       [ 2.14253279,  7.23941366, -2.63605031],
       [-7.7249089 , -6.74945128, -0.87523881],
       [ 0.57963236,  0.89999233,  0.22808379],
       [ 8.45011016,  3.81489682, -5.53018517],
       [ 2.41525632,  1.29280108, -6.23151916],
       [ 9.48636994, -7.58086919,  7.05891809],
       [ 5.19735692, -3.55060186,  1.68258392],
       [-7.49742649, -3.64240583, -6.79203948],
       [ 4.06450451,  5.59003805,  9.05506944],
       [-2.09643346,  2.47204263,  8.51421792]])

In [23]:
velocity=np.zeros((n_particle,3))
velocity

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#intialization of local_best and global_best
best_position=particles.copy()
best_fitness=np.zeros(n_particle)
for i in range(n_particle):
  best_fitness[i]=objective_function(particles[i])

In [25]:
#intialize the global_best
global_best_fitness=best_fitness.min()
global_best_position=best_position[best_fitness.argmin()]
global_best_position

array([ 2.41525632,  1.29280108, -6.23151916])

# Now the optimization steps



```
r1=np.random.rand(n_particle,3)
cognetive_velocity=c1*r1*(best_position-particles)
cognetive_velocity
```



In [26]:
for i in range(max_iteration):
  #update velocity
  r1=np.random.rand(n_particle,3) #this is random vector which we mutliple by the vector of velocity. update cognitive velocity
  r2=np.random.rand(n_particle,3) #this is random vector which we mutliple by the vector of velocity. update global velocity

  cognetive_velocity=c1*r1*(best_position-particles)

  social_velocity=c2*r2*(global_best_position-particles)

  #inertia is w.
  velocity=w * velocity + cognetive_velocity + social_velocity

  #update position
  particles=particles+velocity

  #cliping
  particles=np.clip(particles,bound[0],bound[1])
  #cliping velocity
  velocity = np.clip(velocity, -abs(bound[1]-bound[0]), abs(bound[1]-bound[0]))

  #evaluate
  fitness=np.array([objective_function(p) for p in particles])

  #update best local
  for j in range(n_particle):
    if fitness[j]<best_fitness[j]:
      best_fitness[j]=fitness[j]
      best_position[j]=particles[j].copy()
      #the above is updaing the vector based if new value is better than the current best local only.

  #update global best
  if best_fitness.min()<global_best_fitness:
    global_best_fitness=best_fitness.min()
    global_best_position=best_position[best_fitness.argmin()] #gives the particle the vector

  #inertia decay
  w = 0.9 - (0.5 * i / max_iteration)

  print(f'iteration {i+1}')

  print(f"Global Best Position: {global_best_position}")
  print(f"Global Best Fitness: {global_best_fitness}")




iteration 1
Global Best Position: [ 2.67571965  2.46436286 -3.70360251]
Global Best Fitness: 13.456615592245601
iteration 2
Global Best Position: [ 2.45800397  3.30229454 -5.03406765]
Global Best Fitness: 6.1929808922064655
iteration 3
Global Best Position: [ 2.45800397  3.30229454 -5.03406765]
Global Best Fitness: 6.1929808922064655
iteration 4
Global Best Position: [ 2.51570536  4.45830546 -4.74906218]
Global Best Fitness: 4.061409003999431
iteration 5
Global Best Position: [ 4.36586598  4.30339698 -6.39258046]
Global Best Fitness: 0.7732331014483156
iteration 6
Global Best Position: [ 4.36586598  4.30339698 -6.39258046]
Global Best Fitness: 0.7732331014483156
iteration 7
Global Best Position: [ 4.36586598  4.30339698 -6.39258046]
Global Best Fitness: 0.7732331014483156
iteration 8
Global Best Position: [ 4.36586598  4.30339698 -6.39258046]
Global Best Fitness: 0.7732331014483156
iteration 9
Global Best Position: [ 4.36586598  4.30339698 -6.39258046]
Global Best Fitness: 0.7732331014

# Code For visualization

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D

# Objective function
def objective_function(params):
    x, y, z = params[0], params[1], params[2]
    return (x - 4)**2 + (y - 5)**2 + (z + 6)**2

# Parameters
bound = np.array([-10, 10])
n_particle = 20
max_iteration = 50
c1, c2 = 2.0, 2.0
w_max = 0.9
w_min = 0.4
dim = 3

# Initialize particles
particles = np.random.uniform(bound[0], bound[1], size=(n_particle, dim))
velocity = np.zeros((n_particle, dim))
best_position = particles.copy()
best_fitness = np.array([objective_function(p) for p in particles])

# Initialize global best
global_best_index = best_fitness.argmin()
global_best_position = best_position[global_best_index].copy()
global_best_fitness = best_fitness[global_best_index]

# Store positions for animation
positions_history = [particles.copy()]

# PSO Loop
for iteration in range(max_iteration):
    # Update inertia weight
    w = w_max - (w_max - w_min) * (iteration / max_iteration)

    r1 = np.random.rand(n_particle, dim)
    r2 = np.random.rand(n_particle, dim)

    cognitive_velocity = c1 * r1 * (best_position - particles)
    social_velocity = c2 * r2 * (global_best_position - particles)

    velocity = w * velocity + cognitive_velocity + social_velocity
    particles += velocity
    particles = np.clip(particles, bound[0], bound[1])

    fitness = np.array([objective_function(p) for p in particles])

    # Update personal bests
    improved = fitness < best_fitness
    best_fitness[improved] = fitness[improved]
    best_position[improved] = particles[improved]

    # Update global best
    current_global_best_index = best_fitness.argmin()
    current_global_best_fitness = best_fitness[current_global_best_index]

    if current_global_best_fitness < global_best_fitness:
        global_best_fitness = current_global_best_fitness
        global_best_position = best_position[current_global_best_index].copy()

    positions_history.append(particles.copy())

    print(f"Iteration {iteration+1}: Global Best Fitness = {global_best_fitness:.6f}")

    # Optional early stopping
    if global_best_fitness < 1e-6:
        print("Converged early.")
        break

# Final result
print("\nConverged Global Best Position:", global_best_position)
print("Global Best Fitness:", global_best_fitness)


Iteration 1: Global Best Fitness = 6.507885
Iteration 2: Global Best Fitness = 6.507885
Iteration 3: Global Best Fitness = 6.174307
Iteration 4: Global Best Fitness = 6.174307
Iteration 5: Global Best Fitness = 5.827789
Iteration 6: Global Best Fitness = 1.458288
Iteration 7: Global Best Fitness = 1.458288
Iteration 8: Global Best Fitness = 1.458288
Iteration 9: Global Best Fitness = 0.539004
Iteration 10: Global Best Fitness = 0.539004
Iteration 11: Global Best Fitness = 0.489954
Iteration 12: Global Best Fitness = 0.489954
Iteration 13: Global Best Fitness = 0.489954
Iteration 14: Global Best Fitness = 0.489954
Iteration 15: Global Best Fitness = 0.489954
Iteration 16: Global Best Fitness = 0.334607
Iteration 17: Global Best Fitness = 0.334607
Iteration 18: Global Best Fitness = 0.334607
Iteration 19: Global Best Fitness = 0.334607
Iteration 20: Global Best Fitness = 0.334607
Iteration 21: Global Best Fitness = 0.334607
Iteration 22: Global Best Fitness = 0.267530
Iteration 23: Globa

In [16]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from mpl_toolkits.mplot3d import Axes3D

# Objective function
def objective_function(params):
    x, y, z = params[0], params[1], params[2]
    return (x - 4)**2 + (y - 5)**2 + (z + 6)**2

# Parameters
bound = np.array([-10, 10])
n_particle = 20
max_iteration = 50
c1, c2 = 2.0, 2.0
w_max = 0.9
w_min = 0.4
dim = 3

# Initialize particles
particles = np.random.uniform(bound[0], bound[1], size=(n_particle, dim))
velocity = np.zeros((n_particle, dim))
best_position = particles.copy()
best_fitness = np.array([objective_function(p) for p in particles])

# Initialize global best
global_best_index = best_fitness.argmin()
global_best_position = best_position[global_best_index].copy()
global_best_fitness = best_fitness[global_best_index]

# Store positions for animation
positions_history = [particles.copy()]

# PSO Loop
for iteration in range(max_iteration):
    # Update inertia weight
    w = w_max - (w_max - w_min) * (iteration / max_iteration)

    r1 = np.random.rand(n_particle, dim)
    r2 = np.random.rand(n_particle, dim)

    cognitive_velocity = c1 * r1 * (best_position - particles)
    social_velocity = c2 * r2 * (global_best_position - particles)

    velocity = w * velocity + cognitive_velocity + social_velocity
    particles += velocity
    particles = np.clip(particles, bound[0], bound[1])

    fitness = np.array([objective_function(p) for p in particles])

    # Update personal bests
    improved = fitness < best_fitness
    best_fitness[improved] = fitness[improved]
    best_position[improved] = particles[improved]

    # Update global best
    current_global_best_index = best_fitness.argmin()
    current_global_best_fitness = best_fitness[current_global_best_index]

    if current_global_best_fitness < global_best_fitness:
        global_best_fitness = current_global_best_fitness
        global_best_position = best_position[current_global_best_index].copy()

    positions_history.append(particles.copy())

    print(f"Iteration {iteration+1}: Global Best Fitness = {global_best_fitness:.6f}")

    # Optional early stopping
    if global_best_fitness < 1e-6:
        print("Converged early.")
        break

# Final result
print("\n✅ Converged Global Best Position:", global_best_position)
print("✅ Global Best Fitness:", global_best_fitness)

# ==========================================
# ✅ Animation: Save as 3D GIF
# ==========================================
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

def update(frame):
    ax.clear()
    ax.set_xlim(bound[0], bound[1])
    ax.set_ylim(bound[0], bound[1])
    ax.set_zlim(bound[0], bound[1])
    ax.set_title(f"Iteration {frame+1}", fontsize=12)

    data = positions_history[frame]
    ax.scatter(data[:, 0], data[:, 1], data[:, 2], color='blue', s=50, label='Particles')
    ax.scatter(global_best_position[0], global_best_position[1], global_best_position[2],
               color='red', s=100, marker='*', label='Global Best')

    ax.legend()

# Animate
anim = FuncAnimation(fig, update, frames=len(positions_history), interval=250)

# Save to gif (requires pillow)
anim.save("pso_3d_feto.gif", writer="pillow", fps=5)
plt.close()

print("🎥 GIF saved as 'pso_3d.gif'")


Iteration 1: Global Best Fitness = 0.359883
Iteration 2: Global Best Fitness = 0.359883
Iteration 3: Global Best Fitness = 0.359883
Iteration 4: Global Best Fitness = 0.359883
Iteration 5: Global Best Fitness = 0.359883
Iteration 6: Global Best Fitness = 0.359883
Iteration 7: Global Best Fitness = 0.304320
Iteration 8: Global Best Fitness = 0.304320
Iteration 9: Global Best Fitness = 0.304320
Iteration 10: Global Best Fitness = 0.304320
Iteration 11: Global Best Fitness = 0.304320
Iteration 12: Global Best Fitness = 0.304320
Iteration 13: Global Best Fitness = 0.304320
Iteration 14: Global Best Fitness = 0.304320
Iteration 15: Global Best Fitness = 0.234858
Iteration 16: Global Best Fitness = 0.234858
Iteration 17: Global Best Fitness = 0.234858
Iteration 18: Global Best Fitness = 0.234858
Iteration 19: Global Best Fitness = 0.234858
Iteration 20: Global Best Fitness = 0.234858
Iteration 21: Global Best Fitness = 0.131422
Iteration 22: Global Best Fitness = 0.131422
Iteration 23: Globa